function getFuture() {
  
  var model = '',
      models = {}, 
      factor = '',
      factors = {},
      future = '',
      futures = [
        'Communism (Egalitarianism and Abundance)', 
        'Rentism (Hierarchy and Abundance)', 
        'Socialism (Egalitarianism and Scarcity)', 
        'Exterminism (Hierarchy and Scarcity)'
      ];

  future = futures[Math.floor(Math.random() * futures.length)];
  
  models = {
    communism: [
      'an Airbnb-like platform', 
      'a ridesharing platform', 
      'a TaskRabbit-like service', 
      'a Blue Apron-like service',
      'the Uber', 
      'a crowdsourcing platform',
      'a crowdfunding platform',
      'a crowdfunding platform that collectively buys stock to faciliate shareholder activism',
      'a crowdfunding platform that collectively buys and redistributes land',
      'a gamified crowdsourcing platform',
      'a crowdsourcing platform that aggregates self-tracking data',
      'an intellectual property consortium',
      'a risk management calculator powered by crowdsourcing',
      'an artificial intelligence powered by crowdsourcing',
      'an artificial intelligence, powered by many humans, to automate processes',
      'an artificial intelligence, powered by many humans, to facilitate participatory budgeting',
      'an artificial intelligence, powered by many humans, to facilitate democratic processes',
      'an artificial intelligence to facilitate equality',
      'an AI-powered, Facebook Messenger bot network',  
      'wearble tech that aggregates user data',
      'a knowledge sharing platform',
      'a sharing economy platform that rents boats',
      'a sharing economy platform that rents construction equipment',
      'a sharing economy platform that rents adventure sports gear',
      'a sharing economy platform that rents RVs',
      'a sharing economy platform that rents storage space',
      'a sharing economy platform that rents land',
      'a sharing economy platform that rents drones',
      'a sharing economy platform that rents 3D printers',
      'a decentralized, self-organized, globally distributed community that retrofits abandoned malls',
      'a decentralized, self-organized, globally distributed community that retrofits abandoned missle silos',
      'a decentralized, self-organized, globally distributed community that retrofits abandoned office buildings',
      'a decentralized, self-organized, globally distributed community that retrofits dying office parks',
      'a digital platform that faciliates democratic processes' 
    ],
    rentism: [
      'an Airbnb-like platform', 
      'a ridesharing platform', 
      'a TaskRabbit-like service', 
      'a Blue Apron-like service',
      'the Uber', 
      'a crowdsourcing platform',
      'a crowdfunding platform',
      'a crowdfunding platform that collectively buys stock to faciliate shareholder activism',
      'a crowdfunding platform that collectively buys and redistributes land',
      'a gamified crowdsourcing platform',
      'a crowdsourcing platform that aggregates self-tracking data',
      'an intellectual property consortium',
      'a crowdsourced intellectual property consortium that grants patents',
      'an AI-powered, intellectual property consortium that grants patents',
      'an intellectual property consortium, powered by pirates, that grants patents',
      'a risk management calculator powered by crowdsourcing',
      'an artificial intelligence powered by crowdsourcing',
      'an artificial intelligence, powered by many humans, to automate processes',
      'an artificial intelligence, powered by many humans, to facilitate democratic processes',
      'an artificial intelligence to facilitate equality',
      'an AI-powered, Facebook Messenger bot network',  
      'wearble tech that aggregates user data',
      'a knowledge sharing platform',
      'a sharing economy platform that rents boats',
      'a sharing economy platform that rents luxury yachts',
      'a sharing economy platform that rents private planes',
      'a sharing economy platform that rents construction equipment',
      'a sharing economy platform that rents endangered animals',
      'a sharing economy platform that rents survival gear',
      'a sharing economy platform that rents adventure sports gear',
      'a sharing economy platform that rents RVs',
      'a sharing economy platform that rents storage space',
      'a sharing economy platform that rents land',
      'a sharing economy platform that rents drones',
      'a sharing economy platform that rents 3D printers',
      'a decentralized, self-organized, globally distributed community that retrofits abandoned malls',
      'a decentralized, self-organized, globally distributed community that retrofits abandoned missle silos',
      'a decentralized, self-organized, globally distributed community that retrofits abandoned office buildings',
      'a decentralized, self-organized, globally distributed community that retrofits dying office parks',
      'a decentralized, self-organized, globally distributed community that occupies foreclosed homes', 
      'a digital platform that faciliates democratic processes'
    ],
    socialism: [
      'an Airbnb-like platform', 
      'a ridesharing platform', 
      'a TaskRabbit-like service', 
      'a Blue Apron-like service',
      'the Uber', 
      'a crowdsourcing platform',
      'a crowdfunding platform',
      'a crowdfunding platform that collectively buys stock to faciliate shareholder activism',
      'a crowdfunding platform that collectively buys and redistributes land',
      'a gamified crowdsourcing platform',
      'a crowdsourcing platform that aggregates self-tracking data',
      'an intellectual property consortium',
      'a risk management calculator powered by crowdsourcing',
      'an artificial intelligence powered by crowdsourcing',
      'an artificial intelligence, powered by many humans, to automate processes',
      'an artificial intelligence, powered by many humans, to facilitate participatory budgeting',
      'an artificial intelligence, powered by many humans, to facilitate democratic processes',
      'an artificial intelligence to facilitate equality',
      'an AI-powered, Facebook Messenger bot network',  
      'wearble tech that aggregates user data',
      'a knowledge sharing platform',
      'a sharing economy platform that rents boats',
      'a sharing economy platform that rents construction equipment',
      'a sharing economy platform that rents endangered animals',
      'a sharing economy platform that rents survival gear',
      'a sharing economy platform that rents adventure sports gear',
      'a sharing economy platform that rents RVs',
      'a sharing economy platform that rents storage space',
      'a sharing economy platform that rents land',
      'a sharing economy platform that rents drones',
      'a sharing economy platform that rents 3D printers',
      'a decentralized, self-organized, globally distributed community that retrofits abandoned malls',
      'a decentralized, self-organized, globally distributed community that retrofits abandoned missle silos',
      'a decentralized, self-organized, globally distributed community that retrofits abandoned office buildings',
      'a decentralized, self-organized, globally distributed community that retrofits dying office parks',
      'a digital platform that faciliates democratic processes'
    ],
    exterminism: [
      'an Airbnb-like platform', 
      'a ridesharing platform', 
      'a TaskRabbit-like service', 
      'a Blue Apron-like service',
      'the Uber', 
      'a crowdsourcing platform',
      'a crowdfunding platform',
      'a crowdfunding platform that collectively buys stock to faciliate shareholder activism',
      'a crowdfunding platform that collectively buys and redistributes land',
      'a gamified crowdsourcing platform',
      'a crowdsourcing platform that aggregates self-tracking data',
      'an intellectual property consortium',
      'a crowdsourced intellectual property consortium that grants patents',
      'an AI-powered, intellectual property consortium that grants patents',
      'a risk management calculator powered by crowdsourcing',
      'an artificial intelligence powered by crowdsourcing',
      'an artificial intelligence, powered by many humans, to automate processes',
      'an artificial intelligence, powered by many humans, to facilitate democratic processes',
      'an artificial intelligence to facilitate equality',
      'an AI-powered, Facebook Messenger bot network',  
      'wearble tech that aggregates user data',
      'a knowledge sharing platform',
      'a sharing economy platform that rents boats',
      'a sharing economy platform that rents luxury yachts',
      'a sharing economy platform that rents private planes',
      'a sharing economy platform that rents construction equipment',
      'a sharing economy platform that rents endangered animals',
      'a sharing economy platform that rents survival gear',
      'a sharing economy platform that rents adventure sports gear',
      'a sharing economy platform that rents RVs',
      'a sharing economy platform that rents storage space',
      'a sharing economy platform that rents land',
      'a sharing economy platform that rents drones',
      'a sharing economy platform that rents 3D printers',
      'a decentralized, self-organized, globally distributed community that retrofits abandoned malls',
      'a decentralized, self-organized, globally distributed community that retrofits abandoned missle silos',
      'a decentralized, self-organized, globally distributed community that retrofits abandoned office buildings',
      'a decentralized, self-organized, globally distributed community that retrofits dying office parks',
      'a decentralized, self-organized, globally distributed community that occupies foreclosed homes', 
      'a digital platform that faciliates democratic processes'
    ]
  };

  factors = {
    communism: [
      'researchers, activists, and citizens',
      'solidarity networks',
      'cooperatives',
      'workers\' rights',
      'ending patriarchy',
      'ending white supremacy',
      'prison abolition',
      'senior care',
      'feminists',
      'resisting gentrification',
      'migrant populations',
      'borderless states',
      'chat bots',
      'detention centers',
      'automatic factories',
      'cloud production',
      'distributed manufacturing',
      'mutual aid',
      'forecasting',
      'decolonization',
      're-indigenization',
      'sousveillance',
      'aging',
      'life extension',
      'vulnerable populations',
      'healing intergenerational trauma',
      'illness',
      'public agency',
      'failure',
      'ruin',
      'kindness and curiosity',
      'the colonization of space',
      'hospitality',
      'airport security',
      'unattended baggage',
      'viruses',
      'smart grids',
      'sleep',
      'known unknowns',
      'unknown unknowns',
      'public education',
      'dissapointment',
      'surplus populations',
      '"smart" things',
      '"smart" homes',
      'biotech companies',
      'local food systems',
      'local food production',
      'municipal enterprises',
      'community land trusts',
      'the partnership state',
      'cyborgs',
      'quantified babies',
      'cyberwarfare',
      'lifelong learners',
      'a new model of large-scale worker-owned and community-benefiting businesses',
      'language justice',
      'Community Development Corporations (CDCs)',
      'Community Development Financial Institutions (CDFIs)',
      'Transit-Oriented Development (TOD)',
      'social and economic justice',
      'impact investors',
      'reparations',
      'election reform',
      'transportation infrastructure planning',
      'healthcare reform',
      'solo retreats',
      'solo violin',
      'dance offs',
      'endurance performances',
      'communal meal ideas',
      'community gardens',
      'quiet time',
      'the right to be lazy',
      'therapy',
      'pro-bono legal services',
      'street vendors',
      'unthinking design thinking',
      'poets',
      'accessibility',
      'stem cell research',
      'bioethics research',
      'going off the grid',
      'digital humanitarians',
      'transitioning to a Commons-based society',
      'the equitable distribution of wealth, land, and power',
      'flood prevention',
      'the colonization of virtual worlds',
      'clean energy co-ops',
      'ethical hackers',
      'meditation retreats',
      'conflict negotiators',
      'health care professionals',
      'recovering capitalists',
      'rouge states',
      'love',
      'leisure',
      'the unknown future',
      'the colonization of other planets',
      'strengthening human bonds',
      'biodiversity'
    ],
    rentism: [
      'researchers, activists, and citizens',
      'solidarity networks',
      'pirates',
      'cooperatives',
      'workers\' rights',
      'ending patriarchy',
      'ending white supremacy',
      'prison abolition',
      'life in a police state',
      'senior care',
      'feminists',
      'resisting gentrification',
      'migrant populations',
      'borderless states',
      'chat bots',
      'perpetually unemployed millennials',
      'gated communities',
      'private islands',
      'terrorism paranoia',
      'biological quarantines',
      'ghettos',
      'detention centers',
      'buying off the angry mob',
      'private security',
      'automatic factories',
      'cloud production',
      'distributed manufacturing',
      'private security drones',
      'surveillance drones',
      'humanitarian drones',
      'unpatentable things',
      'copyright cartels',
      'bodyguards',
      'local self-reliance',
      'propaganda',
      'forecasting',
      'sousveillance',
      'surveillance',
      'aging',
      'life extension',
      'vulnerable populations',
      'migrant laborers',
      'undocumented immigrants',
      'systemic collapse',
      'illness',
      'public agency',
      'failure',
      'ruin',
      'the colonization of space',
      'airport security',
      'unattended baggage',
      'viruses',
      'smart grids',
      'domestic workers',
      'sleep',
      'sovereignty',
      'the job insecure',
      'known unknowns',
      'unknown unknowns',
      'workers who refuse work',
      'reform or revolution',
      'public education',
      'dissapointment',
      'vertical slums',
      'surplus populations',
      '"smart" things',
      '"smart" homes',
      'private military contractors',
      'private guards',
      'biotech companies',
      'patent trolls',
      'local food systems',
      'local food production',
      'municipal enterprises',
      'the partnership state',
      'biohackers',
      'cyborgs',
      'quantified babies',
      'billionaire Marxists',
      'biochemical warfare',
      'cyberwarfare',
      'growing collective wealth',
      'lifelong learners',
      'cross-sectoral collaboration',
      'language justice',
      'Community Development Corporations (CDCs)',
      'Community Development Financial Institutions (CDFIs)',
      'Transit-Oriented Development (TOD)',
      'cryptocurrency ponzi schemes',
      'fiscal transparency',
      'social and economic justice',
      'impact investors',
      'the redistribution of wealth',
      'reparations',
      'election reform',
      'entrepreneurs',
      'solopreneurs',
      'solo retreats',
      'solo violin',
      'dance offs',
      'endurance performances',
      'quiet time',
      'navigating in extreme weather conditions',
      'therapy',
      'pro-bono legal services',
      'street vendors',
      'unthinking design thinking',
      'strategic planning',
      'poets',
      'stem cell research',
      'going off the grid',
      'digital humanitarians',
      'the colonization of virtual worlds',
      'meditation retreats',
      'conflict negotiators',
      'health care professionals',
      'recovering socialists',
      'rouge states',
      'love',
      'leisure',
      'the unknown future',
      'arrested protesters',
      'unemployed professionals',
      'unemployed farm hands',
      'the colonization of other planets',
      'strengthening human bonds',
      'exhaustion',
      'biodiversity'
    ],
    socialism: [
      'researchers, activists, and citizens',
      'solidarity networks',
      'cooperatives',
      'workers\' rights',
      'ending patriarchy',
      'ending white supremacy',
      'prison abolition',
      'senior care',
      'feminists',
      'resisting gentrification',
      'climate change adaptation',
      'climate disasters',
      'migrant populations',
      'borderless states',
      'chat bots',
      'detention centers',
      'renewable energy production',
      'automatic factories',
      'cloud production',
      'distributed manufacturing',
      'vertical farming',
      'environmental catastophe prepardness',
      'mutual aid',
      'forecasting',
      'decolonization',
      're-indigenization',
      'sousveillance',
      'aging',
      'life extension',
      'vulnerable populations',
      'healing intergenerational trauma',
      'illness',
      'public agency',
      'kindness and curiosity',
      'the colonization of space',
      'hospitality',
      'airport security',
      'unattended baggage',
      'viruses',
      'a tsunami',
      'smart grids',
      'sleep',
      'known unknowns',
      'unknown unknowns',
      'public education',
      'dissapointment',
      'surplus populations',
      '"smart" things',
      '"smart" homes',
      'biotech companies',
      'local food systems',
      'local food production',
      'municipal enterprises',
      'worker cooperatives',
      'community land trusts',
      'the partnership state',
      'cyborgs',
      'quantified babies',
      'cyberwarfare',
      'lifelong learners',
      'a new model of large-scale worker-owned and community-benefiting businesses',
      'a green economy',
      'language justice',
      'Community Development Corporations (CDCs)',
      'Community Development Financial Institutions (CDFIs)',
      'Transit-Oriented Development (TOD)',
      'social and economic justice',
      'impact investors',
      'reparations',
      'election reform',
      'transportation infrastructure planning',
      'healthcare reform',
      'solo retreats',
      'solo violin',
      'dance offs',
      'endurance performances',
      'communal meal ideas',
      'community gardens',
      'quiet time',
      'navigating in extreme weather conditions',
      'therapy',
      'pro-bono legal services',
      'street vendors',
      'unthinking design thinking',
      'strategic planning',
      'poets',
      'accessibility',
      'stem cell research',
      'bioethics research',
      'going off the grid',
      'digital humanitarians',
      'disaster response',
      'transitioning to a Commons-based society',
      'the equitable distribution of wealth, land, and power',
      'flood prevention',
      'the colonization of virtual worlds',
      'clean energy co-ops',
      'ethical hackers',
      'meditation retreats',
      'conflict negotiators',
      'health care professionals',
      'recovering capitalists',
      'rouge states',
      'love',
      'leisure',
      'the unknown future',
      'the colonization of other planets',
      'strengthening human bonds',
      'strengthening human bonds with nature',
      'exhaustion',
      'biodiversity'
    ],
    exterminism: [
      'researchers, activists, and citizens',
      'solidarity networks',
      'pirates',
      'cooperatives',
      'workers\' rights',
      'ending patriarchy',
      'ending white supremacy',
      'prison abolition',
      'life in a police state',
      'senior care',
      'feminists',
      'resisting gentrification',
      'climate change adaptation',
      'climate disasters',
      'migrant populations',
      'borderless states',
      'chat bots',
      'perpetually unemployed millennials',
      'gated communities',
      'private islands',
      'terrorism paranoia',
      'biological quarantines',
      'ghettos',
      'detention centers',
      'buying off the angry mob',
      'private security',
      'renewable energy production',
      'automatic factories',
      'cloud production',
      'distributed manufacturing',
      'private security drones',
      'surveillance drones',
      'humanitarian drones',
      'vertical farming',
      'preppers and survivalists',
      'bodyguards',
      'environmental catastophe prepardness',
      'local self-reliance',
      'propaganda',
      'forecasting',
      'sousveillance',
      'surveillance',
      'aging',
      'life extension',
      'vulnerable populations',
      'migrant laborers',
      'undocumented immigrants',
      'systemic collapse',
      'illness',
      'public agency',
      'failure',
      'ruin',
      'the colonization of space',
      'airport security',
      'unattended baggage',
      'viruses',
      'a tsunami',
      'smart grids',
      'domestic workers',
      'sleep',
      'sovereignty',
      'the job insecure',
      'known unknowns',
      'unknown unknowns',
      'workers who refuse work',
      'reform or revolution',
      'public education',
      'dissapointment',
      'vertical slums',
      'surplus populations',
      '"smart" things',
      '"smart" homes',
      'private military contractors',
      'private guards',
      'biotech companies',
      'local food systems',
      'local food production',
      'municipal enterprises',
      'the partnership state',
      'biohackers',
      'cyborgs',
      'quantified babies',
      'billionaire Marxists',
      'biochemical warfare',
      'cyberwarfare',
      'growing collective wealth',
      'lifelong learners',
      'cross-sectoral collaboration',
      'language justice',
      'Community Development Corporations (CDCs)',
      'Community Development Financial Institutions (CDFIs)',
      'Transit-Oriented Development (TOD)',
      'cryptocurrency ponzi schemes',
      'fiscal transparency',
      'social and economic justice',
      'impact investors',
      'the redistribution of wealth',
      'reparations',
      'election reform',
      'entrepreneurs',
      'solopreneurs',
      'solo retreats',
      'solo violin',
      'dance offs',
      'endurance performances',
      'quiet time',
      'navigating in extreme weather conditions',
      'therapy',
      'pro-bono legal services',
      'street vendors',
      'unthinking design thinking',
      'poets',
      'stem cell research',
      'going off the grid',
      'digital humanitarians',
      'disaster response',
      'flood prevention',
      'the colonization of virtual worlds',
      'clean energy co-ops',
      'meditation retreats',
      'conflict negotiators',
      'recovering socialists',
      'rouge states',
      'love',
      'leisure',
      'the unknown future',
      'arrested protesters',
      'unemployed professionals',
      'unemployed farm hands',
      'the colonization of other planets',
      'strengthening human bonds',
      'strengthening human bonds with nature',
      'exhaustion'
    ]
  };

  if (future === 'Communism (Egalitarianism and Abundance)'){
    model = models.communism[Math.floor(Math.random() * models.communism.length)];
    factor = factors.communism[Math.floor(Math.random() * factors.communism.length)];
  } else if (future === 'Rentism (Hierarchy and Abundance)') {
    model = models.rentism[Math.floor(Math.random() * models.rentism.length)];
    factor = factors.rentism[Math.floor(Math.random() * factors.rentism.length)];
  } else if (future === 'Socialism (Egalitarianism and Scarcity)') {
    model = models.socialism[Math.floor(Math.random() * models.socialism.length)];
    factor = factors.socialism[Math.floor(Math.random() * factors.socialism.length)];
  } else if (future === 'Exterminism (Hierarchy and Scarcity)') {
    model = models.exterminism[Math.floor(Math.random() * models.exterminism.length)];
    factor = factors.exterminism[Math.floor(Math.random() * factors.exterminism.length)];
  }
  
  $(".future").append('<span class="scenario">Scenario: ' + future +'</span><br/><span class="design">Design '+ model + ' for ' + factor + '</span>');
  console.log(future + '\n' + 'Design ' + model + ' for ' + factor);
}

$(".makefuture").on('click', function(){
  $(".future").empty();
  getFuture(); 
});


  // var bizmodels = [
  //   'an Airbnb-like platform', 
  //   'a ridesharing platform', 
  //   'a TaskRabbit-like service', 
  //   'a Blue Apron-like service',
  //   'the Uber', 
  //   'a crowdsourcing platform',
  //   'a crowdfunding platform',
  //   'a crowdfunding platform that collectively buys stock to faciliate shareholder activism',
  //   'a crowdfunding platform that collectively buys and redistributes land',
  //   'a gamified crowdsourcing platform',
  //   'a crowdsourcing platform that aggregates self-tracking data',
  //   'an intellectual property consortium',
  //   'a crowdsourced intellectual property consortium that grants patents',
  //   'an AI-powered, intellectual property consortium that grants patents',
  //   'an intellectual property consortium, powered by pirates, that grants patents',
  //   'a risk management calculator powered by crowdsourcing',
  //   'an artificial intelligence powered by crowdsourcing',
  //   'an artificial intelligence, powered by many humans, to automate processes',
  //   'an artificial intelligence, powered by many humans, to facilitate participatory budgeting',
  //   'an artificial intelligence, powered by many humans, to facilitate democratic processes',
  //   'an artificial intelligence to facilitate equality',
  //   'an AI-powered, Facebook Messenger bot network',  
  //   'wearble tech that aggregates user data',
  //   'a knowledge sharing platform',
  //   'a sharing economy platform that rents boats',
  //   'a sharing economy platform that rents luxury yachts',
  //   'a sharing economy platform that rents private planes',
  //   'a sharing economy platform that rents construction equipment',
  //   'a sharing economy platform that rents endangered animals',
  //   'a sharing economy platform that rents survival gear',
  //   'a sharing economy platform that rents adventure sports gear',
  //   'a sharing economy platform that rents RVs',
  //   'a sharing economy platform that rents storage space',
  //   'a sharing economy platform that rents land',
  //   'a sharing economy platform that rents drones',
  //   'a sharing economy platform that rents 3D printers',
  //   'a decentralized, self-organized, globally distributed community that retrofits abandoned malls',
  //   'a decentralized, self-organized, globally distributed community that retrofits abandoned missle silos',
  //   'a decentralized, self-organized, globally distributed community that retrofits abandoned office buildings',
  //   'a decentralized, self-organized, globally distributed community that retrofits dying office parks',
  //   'a decentralized, self-organized, globally distributed community that occupies foreclosed homes', 
  //   'a digital platform that faciliates democratic processes'   
  // ];

  // var bizmodel = bizmodels[Math.floor(Math.random() * bizmodels.length)];

  // var xfactors = [
  //   'researchers, activists, and citizens',
  //   'solidarity networks',
  //   'pirates',
  //   'cooperatives',
  //   'workers\' rights',
  //   'ending patriarchy',
  //   'ending white supremacy',
  //   'prison abolition',
  //   'life in a police state',
  //   'senior care',
  //   'feminists',
  //   'resisting gentrification',
  //   'climate change adaptation',
  //   'climate disasters',
  //   'migrant populations',
  //   'borderless states',
  //   'chat bots',
  //   'perpetually unemployed millennials',
  //   'gated communities',
  //   'private islands',
  //   'terrorism paranoia',
  //   'biological quarantines',
  //   'ghettos',
  //   'detention centers',
  //   'buying off the angry mob',
  //   'private security',
  //   'renewable energy production',
  //   'automatic factories',
  //   'cloud production',
  //   'distributed manufacturing',
  //   'private security drones',
  //   'surveillance drones',
  //   'humanitarian drones',
  //   'vertical farming',
  //   'unpatentable things',
  //   'copyright cartels',
  //   'preppers and survivalists',
  //   'bodyguards',
  //   'environmental catastophe prepardness',
  //   'local self-reliance',
  //   'mutual aid',
  //   'propaganda',
  //   'forecasting',
  //   'decolonization',
  //   're-indigenization',
  //   'sousveillance',
  //   'surveillance',
  //   'aging',
  //   'life extension',
  //   'vulnerable populations',
  //   'healing intergenerational trauma',
  //   'migrant laborers',
  //   'undocumented immigrants',
  //   'systemic collapse',
  //   'illness',
  //   'public agency',
  //   'failure',
  //   'ruin',
  //   'kindness and curiosity',
  //   'the colonization of space',
  //   'hospitality',
  //   'airport security',
  //   'unattended baggage',
  //   'viruses',
  //   'a tsunami',
  //   'smart grids',
  //   'domestic workers',
  //   'sleep',
  //   'sovereignty',
  //   'the job insecure',
  //   'known unknowns',
  //   'unknown unknowns',
  //   'workers who refuse work',
  //   'reform or revolution',
  //   'public education',
  //   'dissapointment',
  //   'vertical slums',
  //   'surplus populations',
  //   '"smart" things',
  //   '"smart" homes',
  //   'private military contractors',
  //   'private guards',
  //   'biotech companies',
  //   'patent trolls',
  //   'local food systems',
  //   'local food production',
  //   'municipal enterprises',
  //   'worker cooperatives',
  //   'community land trusts',
  //   'the partnership state',
  //   'biohackers',
  //   'cyborgs',
  //   'quantified babies',
  //   'billionaire Marxists',
  //   'biochemical warfare',
  //   'cyberwarfare',
  //   'growing collective wealth',
  //   'lifelong learners',
  //   'a new model of large-scale worker-owned and community-benefiting businesses',
  //   'a green economy',
  //   'cross-sectoral collaboration',
  //   'language justice',
  //   'Community Development Corporations (CDCs)',
  //   'Community Development Financial Institutions (CDFIs)',
  //   'Transit-Oriented Development (TOD)',
  //   'cryptocurrency ponzi schemes',
  //   'fiscal transparency',
  //   'social and economic justice',
  //   'impact investors',
  //   'the redistribution of wealth',
  //   'reparations',
  //   'election reform',
  //   'transportation infrastructure planning',
  //   'healthcare reform',
  //   'entrepreneurs',
  //   'solopreneurs',
  //   'solo retreats',
  //   'solo violin',
  //   'dance offs',
  //   'endurance performances',
  //   'communal meal ideas',
  //   'community gardens',
  //   'quiet time',
  //   'navigating in extreme weather conditions',
  //   'the right to be lazy',
  //   'therapy',
  //   'pro-bono legal services',
  //   'street vendors',
  //   'unthinking design thinking',
  //   'strategic planning',
  //   'poets',
  //   'accessibility',
  //   'stem cell research',
  //   'bioethics research',
  //   'going off the grid',
  //   'digital humanitarians',
  //   'disaster response',
  //   'transitioning to a Commons-based society',
  //   'the equitable distribution of wealth, land, and power',
  //   'flood prevention',
  //   'the colonization of virtual worlds',
  //   'clean energy co-ops',
  //   'ethical hackers',
  //   'meditation retreats',
  //   'conflict negotiators',
  //   'health care professionals',
  //   'recovering capitalists',
  //   'recovering socialists',
  //   'rouge states',
  //   'love',
  //   'leisure',
  //   'the unknown future',
  //   'arrested protesters',
  //   'unemployed professionals',
  //   'unemployed farm hands',
  //   'the colonization of other planets',
  //   'strengthening human bonds',
  //   'strengthening human bonds with nature',
  //   'exhaustion',
  //   'biodiversity'
  //   ];

  // var xfactor = xfactors[Math.floor(Math.random() * xfactors.length)];

