function getFuture() {
  var futures = ['Communism (Egalitarianism and Abundance)', 'Rentism (Hierarchy and Abundance)', 'Socialism (Egalitarianism and Scarcity)', 'Exterminism (Hierarchy and Scarcity)'];
  var future = futures[Math.floor(Math.random() * futures.length)];
  
  var bizmodels = [
    'an Airbnb-like platform', 
    'a ridesharing platform', 
    'a TaskRabbit-like service', 
    'a subscription service', 
    'a crowdsourcing platform',
    'a crowdfunding platform',
    'a crowdfunding platform that collectively buys stock to faciliate shareholder activism',
    'a crowdfunding platform that collectively buys and redistributes land',
    'a gamified crowdsourcing platform',
    'an assistive technology powered by crowdsourcing', 
    'a crowdsourcing platform that aggregates self-tracking data',
    'an intellectual property consortium powered by crowdsourcing that grants patents',
    'an intellectual property consortium powered by artificial intelligence that grants patents',
    'an intellectual property consortium powered by pirates that grants patents',
    'a risk management calculator powered by crowdsourcing',
    'an artificial intelligence powered by crowdsourcing',
    'an artificial intelligence powered by crowdsourcing that automates processes',
    'an artificial intelligence powered by crowdsourcing to facilitate participatory budgeting',
    'an artificial intelligence powered by crowdsourcing to facilitate democratic processes',
    'an AI powered Facebook Messenger bot network',   
    'wearble tech that aggregates user data',
    'a knowledge sharing platform',
    'a sharing economy platform that rents boats',
    'a sharing economy platform that rents luxury yachts',
    'a sharing economy platform that rents private planes',
    'a sharing economy platform that rents construction equipment',
    'a sharing economy platform that rents endangered animals',
    'a sharing economy platform that rents survival gear',
    'a sharing economy platform that rents adventure sports gear',
    'a sharing economy platform that rents RVs',
    'a sharing economy platform that rents storage space',
    'a sharing economy platform that rents land',
    'a sharing economy platform that rents power tools',
    'a sharing economy platform that rents 3D printers',
    'a gig economy platform powered by blockchain technology',
    'a decentralized, self-organized, globally distributed community that retrofits dead malls',
    'a decentralized, self-organized, globally distributed community that retrofits abandoned missle silos',
    'a decentralized, self-organized, globally distributed community that retrofits abandoned office buildings',
    'a decentralized, self-organized, globally distributed community that retrofits dying office parks',
    'a decentralized, self-organized, globally distributed community that occupies foreclosed homes', 
    'a digital platform that faciliates democratic processes'   
  ];

  var bizmodel = bizmodels[Math.floor(Math.random() * bizmodels.length)];

  var xfactors = [
    'researchers, activists, and citizens',
    'solidarity networks',
    'pirates',
    'cooperatives',
    'workers\' rights',
    'ending patriarchy',
    'ending white supremacy',
    'prison abolition',
    'life in a police state',
    'senior care',
    'feminists',
    'resisting gentrification',
    'climate change adaptation',
    'climate disasters',
    'migrant populations',
    'borderless states',
    'survivalists',
    'chat bots',
    'perpetually unemployed millennials',
    'gated communities',
    'private islands',
    'terrorism paranoia',
    'biological quarantines',
    'ghettos',
    'detention centers',
    'buying off the angry mob',
    'private security',
    'renewable energy production',
    'automatic factories',
    'cloud production or distributed manufacturing',
    'private security drones',
    'surveillance drones',
    'humanitarian drones',
    'vertical farming',
    'unpatentable things',
    'copyright cartels',
    'preppers',
    'bodyguards',
    'environmental catastophe prepardness',
    'local self-reliance',
    'mutual aid',
    'propaganda',
    'forecasting',
    'decolonization',
    're-indigenization',
    'sousveillance',
    'surveillance',
    'aging',
    'life extension',
    'vulnerable populations',
    'healing intergenerational trauma',
    'migrant laborers',
    'undocumented immigrants',
    'systemic collapse',
    'illness',
    'public agency',
    'failure',
    'ruin',
    'kindness and curiosity',
    'the colonization of space',
    'hospitality',
    'airport security',
    'unattended baggage',
    'viruses',
    'a tsunami',
    'smart grids',
    'domestic workers',
    'sleep',
    'sovereignty',
    'the job insecure',
    'known unknowns',
    'workers who refuse work',
    'reform or revolution',
    'public education',
    'dissapointment',
    'vertical slums',
    'surplus populations',
    '"smart" things',
    '"smart" homes',
    'private military contractors',
    'private guards',
    'biotech companies',
    'patent trolls',
    'internet trolls',
    'fighting internet trolls',
    'local food systems',
    'local food production',
    'municipal enterprises',
    'worker cooperatives',
    'community land trusts',
    'the partnership state',
    'quantified selfies',
    'body hacking',
    'quantified babies',
    'billionaire Marxists',
    'biochemical warfare',
    'cyberwarfare',
    'growing collective wealth',
    'lifelong learners',
    'a new model of large-scale worker-owned and community-benefiting businesses',
    'a green economy',
    'cross-sectoral collaboration',
    'language justice',
    'Community Development Corporations (CDCs)',
    'Community Development Financial Institutions (CDFIs)',
    'Transit-Oriented Development (TOD)',
    'cryptocurrency ponzi schemes',
    'fiscal transparency',
    'social and economic justice',
    'impact investors',
    'the redistribution of wealth',
    'reparations',
    'election reform',
    'transportation infrastructure planning',
    'healthcare reform',
    'entrepreneurs',
    'solopreneurs',
    'solo retreats',
    'solo violin',
    'dance offs',
    'endurance performances',
    'communal meal ideas',
    'community gardens',
    'quiet time',
    'navigating in extreme weather conditions',
    'the right to be lazy',
    'therapy',
    'pro-bono legal services',
    'street vendors',
    'unthinking design thinking',
    'strategic planning',
    'poets',
    'accessibility',
    'stem cell research',
    'bioethics research',
    'going off the grid',
    'digital humanitarians',
    'disaster response',
    'transitioning to a Commons-based society',
    'the equitable distribution of wealth, land, and power',
    'flood prevention',
    'the colonization of virtual worlds',
    'clean energy coops',
    'ethical hackers'
    ];

  var xfactor = xfactors[Math.floor(Math.random() * xfactors.length)];
    
  $(".future").append('<span class="scenario">Scenario: ' + future +'</span><br/><span class="design">Design '+ bizmodel + ' for ' + xfactor + '</span>');
  console.log(future);
}


$(".makefuture").on('click', function(){
  $(".future").empty();
  getFuture();
  console.log(Math.random()); 
});
