var topic, 
    medium, 
    adjective,
    adjective2, 
    adverb, 
    gerund, 
    topicUrl, 
    mediumUrl, 
    adjectiveUrl, 
    adverbUrl,
    gerundUrl;


function pickRandom(){

  var top = Math.floor((topicList.topics.length - 1)*Math.random());
  console.log("top is "+ top);
  topic = topicList.topics[top].topic;
  topicUrl = topicList.topics[top].url;
  console.log(topic);

  var med = Math.floor((mediumList.mediums.length - 1)*Math.random());
  console.log("med is "+ med);
  medium = mediumList.mediums[med].medium;
  mediumUrl = mediumList.mediums[med].url;
  console.log(medium);

  var adj = Math.floor((adjectiveList.adjectives.length - 1)*Math.random());
  console.log("adj is "+ adj);
  adjective = adjectiveList.adjectives[adj].adj;
  adjectiveUrl = adjectiveList.adjectives[adj].url;
  console.log(adjective);

  var adj2 = Math.floor((adjectiveList.adjectives.length - 1)*Math.random());
  console.log("adj2 is "+ adj2);
  adjective2 = adjectiveList.adjectives[adj2].adj;
  adjectiveUrl2 = adjectiveList.adjectives[adj].url;
  console.log(adjective2);

  var adv = Math.floor((adverbList.adverbs.length - 1)*Math.random());
  console.log("adv is "+ adv);
  adverb = adverbList.adverbs[adv].adverb;
  adverbUrl = adverbList.adverbs[adv].url;
  console.log(adverb);

  var ger = Math.floor((gerundList.gerunds.length - 1)*Math.random());
  console.log("ger is "+ ger);
  gerund = gerundList.gerunds[ger].gerund;
  gerundUrl = gerundList.gerunds[ger].url;
  console.log(gerund);

}



function updateArtProjectGenerator(){
    pickRandom();

    r = Math.floor(13*Math.random());

    if (r == 0){
      $(".newproject").append("<span>Commission " + medium + "<sup class='hint--top' data-hint='We recommend: "+ mediumUrl + "'>1</sup>" + " about " + topic + ", made " + adverb + "</span>");
    }
    else if (r == 1){
      $(".newproject").append("<span>Commission " + medium + "<sup class='hint--top' data-hint='We recommend: "+ mediumUrl + "'>1</sup>" +  " about " + topic + "</span>");
    }
    else if (r == 2){
      $(".newproject").append("<span>Commission " + medium + "<sup class='hint--top' data-hint='We recommend: "+ mediumUrl + "'>1</sup>" +  " about " + topic + " generated by " + gerund + "</span>");
    }
    else if (r == 3){ 
      $(".newproject").append("<span>Commission " + medium + "<sup class='hint--top' data-hint='We recommend: "+ mediumUrl + "'>1</sup>" +  " about " + topic + " generated by " + gerund + " " + adverb + "</span>");
    }
    else if (r == 4){
      $(".newproject").append("<span>Commission " + adjective + " " + medium + "<sup class='hint--top' data-hint='We recommend: " + mediumUrl + "'>1</sup>" + "</span>");
    }
    else if (r == 5){
      $(".newproject").append("<span>Commission " + adjective + " " + medium + "<sup class='hint--top' data-hint='We recommend: " + mediumUrl + "'>1</sup>" + " about " + topic + "</span>");
    }
    else if (r == 6){
      $(".newproject").append("<span>Commission " + adjective + " " + medium + "<sup class='hint--top' data-hint='We recommend: " + mediumUrl + "'>1</sup>" + " about " + topic + ", made " + adverb + "</span>");
    }
    else if (r == 7){
      $(".newproject").append("<span>Commission " + adjective + " " + medium + "<sup class='hint--top' data-hint='We recommend: " + mediumUrl + "'>1</sup>" + " about " + topic + " generated by " + gerund + "</span>");
    }
    else if (r == 8){
      $(".newproject").append("<span>Commission " + adjective + " " + medium + "<sup class='hint--top' data-hint='We recommend: " + mediumUrl + "'>1</sup>" + " about " + topic + " generated by " + gerund + " " + adverb + "</span>");
    }
    else if (r == 9){
      $(".newproject").append("<span>Commission " + adjective + " " + medium + "<sup class='hint--top' data-hint='We recommend: " + mediumUrl + "'>1</sup>" + " about " + adjective2 + " " + topic + "</span>");
    }
    else if (r == 10){
      $(".newproject").append("<span>Commission " + adjective + " " + medium + "<sup class='hint--top' data-hint='We recommend: " + mediumUrl + "'>1</sup>" + " about " + adjective2 + " " + topic + ", made " + adverb + "</span>");
    }
    else if (r == 11){
      $(".newproject").append("<span>Commission " + adjective + " " + medium + "<sup class='hint--top' data-hint='We recommend: " + mediumUrl + "'>1</sup>" + " about " + topic + " generated by " + gerund + "</span>");
    }
    else if (r == 12){
      $(".newproject").append("<span>Commission " + adjective + " " + medium + "<sup class='hint--top' data-hint='We recommend: " + mediumUrl + "'>1</sup>" + " about " + topic + " generated by " + gerund + " " + adverb + "</span>");
    }
    
}

$(".makeart").on('click', function(){
  $(".newproject").empty();
  updateArtProjectGenerator();
});

